name: "SDR Reviewer"
description: "Scan architectures for security threats"

inputs:
  diagrams:
    description: "Folder of architecture diagrams"
    required: true
  output_filename:
    description: "Filename for the analysis"
    required: false
    default: "analysis.md"

runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install dependencies
      run: |
        make -C ${{ github.action_path }} setup
      shell: bash

    - name: Authenticate to Google Cloud Platform
      id: auth
      uses: google-github-actions/auth@v2
      with:
        export_environment_variables: true
        create_credentials_file: true
        access_token_scopes: https://www.googleapis.com/auth/cloud-platform
        token_format: "access_token"
        workload_identity_provider: projects/180906254540/locations/global/workloadIdentityPools/cicd/providers/github
        service_account: github@pt-cicd.iam.gserviceaccount.com

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Run AI Analysis
      run: |
        ${{ github.action_path }}/sak/bin/sak sdr -arc ${{ inputs.diagrams }} --output_filename ${{ inputs.output_filename }} --output_format markdown
      shell: bash

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: Security Review
        path: ${{ inputs.output_filename }}
