vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 300
  }
}
pci-gw: pt-prod-pci-gw {
  i: GKE Ingress

  gke: {
    p_gw: Tyk Gateway {
      style.multiple: true
    }

    p_d: Tyk Dashboard {
      style.multiple: true
    }

    p_gw -> p_d: Polls {
      style.stroke-dash: 3
    }
  }

  i -> gke.p_gw
  i -> gke.p_d
}

pt-svc: pt-prod-svc {
  lb_i7: K8S API Gateway
  gke: {
    p_svc: Backend Service {
      style.multiple: true
    }
  }

  lb_i7 -> gke.p_svc
}

pt-pci: pt-prod-pci-svc {
  style: {
    opacity: 0.4
  }
  lb_i7: K8S API Gateway {
    style: {
      opacity: 0.4
    }
  }
}

pci-gw.gke.p_gw -> pt-svc.lb_i7: Private Service Connect
pci-gw.gke.p_gw -> pt-pci.lb_i7: {
  style: {
    stroke-dash: 3
    opacity: 0.4
  }
}

user: User {
  shape: person
}

user -> pci-gw.i
